import type { NextPage } from 'next'
import Head from 'next/head'
import Image from 'next/image'
import styles from '../styles/Home.module.css'
import { PrismaClient } from "@prisma/client";

const prisma = new PrismaClient()

export async function getServerSideProps() {
  const decks = await prisma.deck.findMany()
  console.log({decks})
  return {
    props: {
      decks: decks
    }
  }
}
const Home: NextPage = ({decks}: any) => {
  console.log({decks})
  const saveDeck = async () => {
    const body = { name: `Created Deck ${Math.random()}` }
    const response = await fetch(`/api/decks`, {
        method: 'POST',
        body: JSON.stringify(body),
      })
    if(!response.ok) throw new Error(response.statusText)
    const responseJson = await response.json()
    console.log({responseJson})
  }
  return (
    <div className={styles.container}>
      <Head>
        <title>Create Next App</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>

      <main className={styles.main}>
        <h1 className={styles.title}>
          Welcome to <a href="https://nextjs.org">Next.js!</a>
        </h1>

        <div className={styles.grid}>
            <h2>Decks added to the database &rarr;</h2>
            {decks.map((deck: any) => <p>{deck.name}</p>)}
         

          {/* <a href="https://nextjs.org/learn" className={styles.card}>
            <h2>Learn &rarr;</h2>
            <p>Learn about Next.js in an interactive course with quizzes!</p>
          </a>

          <a
            href="https://github.com/vercel/next.js/tree/master/examples"
            className={styles.card}
          >
            <h2>Examples &rarr;</h2>
            <p>Discover and deploy boilerplate example Next.js projects.</p>
          </a>

          <a
            href="https://vercel.com/new?utm_source=create-next-app&utm_medium=default-template&utm_campaign=create-next-app"
            className={styles.card}
          >
            <h2>Deploy &rarr;</h2>
            <p>
              Instantly deploy your Next.js site to a public URL with Vercel.
            </p>
          </a> */}
        </div>
        <button onClick={() => saveDeck()}>SAVE DECK</button>
      </main>

      <footer className={styles.footer}>
        <a
          href="https://vercel.com?utm_source=create-next-app&utm_medium=default-template&utm_campaign=create-next-app"
          target="_blank"
          rel="noopener noreferrer"
        >
          Powered by{' '}
          <span className={styles.logo}>
            <Image src="/vercel.svg" alt="Vercel Logo" width={72} height={16} />
          </span>
        </a>
      </footer>
    </div>
  )
}

export default Home
